---
title: "Final Project"
author: "Anish Shenoy, Jae Yoon Kim"
date: "11/25/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstanarm)
```

### Import and Merge data

First, import the First Street Foundation (FSF) Flood Risk Summary Statistics by zip
found here: https://registry.opendata.aws/fsf-flood-risk/?fbclid=IwAR2JUyZWXcXiKdXuXMXON-1VmcUm6RpCnUVXMiydCrrDCaXHg41zdkD-iI8
``` {r echo=TRUE, message=FALSE}
zip_risk <- read_csv("data/fsf/v1.1/Zip_level_risk_FEMA_FSF_v1.1.csv")
zip_risk
```
<br>

Next, import data about each zip code in the US uing the tidycensus package
``` {r echo=TRUE, message=FALSE}
library(tidycensus)
census_api_key("0a473d1b1e161d8f87da3ad85e59af583f28f1d6")

# Variable codes found here: 
# https://api.census.gov/data/2010/dec/sf1/variables.html
# P013001: MEDIAN AGE
# H006001: TOTAL ALL RACES IN HOUSEHOLD
# H006002: TOTAL HOUSEHOLDER WHITE ALONE
# H006003: TOTAL BLACK/AFRICAN-AMERICAN ALONE
zip_data <- get_decennial(geography = "zcta",
                          variables = c("P013001", "H006001", "H006002", "H006003"),
                          year = 2010,
                          output = "wide") %>%
  rename(Median.age = P013001,
         Total.pop = H006001,
         Total.white = H006002,
         Total.black = H006003)
zip_data
```
<br>

Finally, merge the the data by zip code
``` {r echo=TRUE}
merged <- inner_join(zip_data, zip_risk, by = c("GEOID" = "zcta5ce")) %>%
  select(-NAME)

merged
```
### Preliminary Data Exploration
